### ISSUE TITLE
Closing of an alert in ZMON is not synched to the paging system

### ISSUE THREAD

**Issue by rajatparida86** [zalando-zmon/zmon-worker#369] opened 2018-10-05 14:54 UTC
If a ZMON alert closes itself, sometimes this does not trigger a closure of the alert in the paging provided. Internal ref: 104

**Comment by laceyallyn** [comment] 2019-08-23 14:26
Closing as duplicate of https://github.com/zalando-zmon/zmon-worker/issues/369

**Closed by laceyallyn** 2019-08-23 14:26 UTC
Labels: bug
